//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopWinform.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oder()
        {
            this.OrderInfoes = new HashSet<OrderInfo>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Status { get; set; }
        public int Account { get; set; }
        public Nullable<int> Customer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Customer Customer1 { get; set; }
    }
}
